---
title: "Thanks for stopping by. Have a look around."
---




Hi, I'm Feven Asefaha. 

My professional goals center around pulling insights and analyzing data in service of helping organizations improve health outcomes more efficiently. To that end, I have experience utilizing a wide range of data tools (R/tidyverse, SAS, SQL, Qlikview, etc) to communicate and engage. Like any scientist, I value collaborating with and learning from my peers. 

Most recently, I worked as a Healthcare Data Analyst at Milliman's Health Practice in NYC. While there, I worked on product, as well as several additional claims analytics projects, with some resulting in [white papers](https://www.milliman.com/en/insight/how-current-part-d-risk-scores-could-interact-with-pointofsale-rebates).

Before that, I was a Master's student in the Biostatistics department at Columbia's Mailman School of Public Health. My master's project looked at the occurrence of waterborne illness among consumers of [SWN's](https://www.safewaternetwork.org/) sustainable water systems. 
 
I obtained my BS from Cornell University in 2015. During college, I gained research experience in biochemistry and collective behavior, and completed an internship in content development at the [Lab of O](https://www.birds.cornell.edu/home/). After college, I worked as a youth advocate, and as a biologist with New York City's [Department of Health](http://www1.nyc.gov/site/doh/index.page). 

Born and raised in [The Bronx](https://www.atlasobscura.com/things-to-do/bronx-new-york/places?page=1).




